### ISSUE TITLE
Isn't it better to make CMS and then use it for your class blog?

### ISSUE THREAD

**Issue by sentialx** [xNerhu22/MyClassBlog#2]
You can try making a Content Management System for everyone and use it for your personal purposes, instead of creating additional repository for your class blog. Isn't it better idea?

**Comment by xNerhu22** [comment]
Tobie naprawę się nudzi XD

**Comment by xNerhu22** [comment]
I dont't think that must be Content Management System.I cant't write panel like wordpress alone. This is too much work for one guy. Btw. You can personalize the blog.

**Comment by Sential** [comment]
No, it's not too much, you are just so fat

**Comment by xNerhu22** [comment]
You're fat too.

**Comment by Sential** [comment]
fuj
