### ISSUE TITLE
hey How can i use it

### ISSUE THREAD

**Issue by Doordoorjay** [xNerhu22/MyClassBlog#3]
i have an server,how can let blog and control panel work?

**Comment by xnerhu** [comment]
Hello,
I'm sorry for being late :(

First you must have installed MongoDB, NodeJS and Python (for bcrypt)
On your local computer build the blog using `npm run build:production` and upload it to your server.
Then you need to install node modules with `npm install` on your server (in folder that blog files are uploaded)
To start server, use command `node index` or `pm2 start index` (to keep node proccess)

Later I'll write file that will help to create first admin account.
